image: andyg/nodejs-ci
script:
  - echo 'Africa/Johannesburg' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - npm install --verbose -g grunt-cli
  - cd /var/cache/drone/src/github.com/andy-g/PiDashboard
  - npm install --verbose
  - grunt
notify:
  email:
    recipients:
      - andy@ignitionroom.com
    on_success: false
    on_failure: true
cache:
  - /root/.npm
  #- /tmp/npm-0/.npm
  
  #- /usr/local/lib/node_modules
  # gitter:
  #   room_id: 06821336092b9a52c252
  #   token: 20f6d881dbd52dbd6087
  #   on_started: true
  #   on_success: true
  #   on_failure: true
